### ISSUE TITLE
What happened to `@sphido/markdown`?

### ISSUE THREAD

**Issue by mrkev** [sphido/sphido#19]
Hello,

I was trying to install the dependencies to my blog, but it fails:

```
blog % npm i
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@sphido/markdown/-/markdown-1.1.0.tgz - Not found
npm error 404
npm error 404  '@sphido/markdown@https://registry.npmjs.org/@sphido/markdown/-/markdown-1.1.0.tgz' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

npm error A complete log of this run can be found in: /Users/kevin/.npm/_logs/2024-08-10T00_13_57_522Z-debug-0.log
```

I noticed `@sphido/markdown` is nowhere to be found in the npm registry:

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/4b8dde9a-70a7-43c4-b7e1-e1c6d18a74a3">

Is there anywhere I can find the code for this deleted package? It's very unfortunate that it was removed as opposed to just staying deprecated. Thanks for the work on sphido btw, looking forward to finding where I can find this source so I can update my blog haha

**Comment by mrkev** [comment]
Figured it out!

Found the commit where it was deleted: https://github.com/sphido/sphido/commit/c42bfc9691b8cf3c09fe50cc5499ca8a8ae0c6fa

And the last commit with it: https://github.com/sphido/sphido/commit/054d2460c155307094dbfa65a72db06b2049a391

All good!

**Comment by OzzyCzech** [comment]
It was removed in favor of plain markdown processing with `marked` or some other library.

Check https://sphido.cz/
